site_name: WIS2 in a box training
site_description: "WIS2 in a box (wis2box) is a Free and Open Source (FOSS) Reference Implementation of a WMO WIS2 Node. The project provides a plug and play toolset to ingest, process, and publish weather/climate/water data using standards-based approaches in alignment with the WIS2 principles. wis2box also provides access to all data in the WIS2 network. wis2box is designed to have a low barrier to entry for data providers, providing enabling infrastructure and services for data discovery, access, and visualization."
site_author: World Meteorological Organization
copyright: "&copy; 2023 World Meteorological Organization"
site_url: https://training.wis2box.wis.wmo.int
#repo_url: https://github.com/World-Meteorological-Organization/wis2box-training
#edit_uri: tree/main/documentation/docs

docs_dir: docs
site_dir: /tmp/html

strict: true

use_directory_urls: true

theme:
    name: material
    palette:
        scheme: default
    features:
        - navigation.indexes
        - content.code.copy
    favicon: https://public.wmo.int/sites/all/themes/wmo/favicon.ico
    logo: assets/img/wmo-logo.png
    # custom_dir: overrides  # adjust to your layout

plugins:
    - search
    - awesome-pages
    - table-reader
    - i18n:
        docs_structure: folder
        languages:
          - locale: en
            default: true
            name: English
            build: true

markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - meta
    - pymdownx.details
    - pymdownx.superfences
    - tables

extra_css:
    - assets/css/custom.css
